---
# LoadBalancer Service used to access kibana
apiVersion: v1
kind: Service
metadata:
  name: kibana-loadbalancer
  namespace: kube-system
  labels:
    k8s-app: kibana-loadbalancer
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Kibana"
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: kibana-logging

