---
# This ClusterIP service will be used for internal communications within the K8s cluster
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
  selector:
    k8s-app: elasticsearch-logging
---
# The LoadBalancer Service for accessing the ElasticSearch cluster from outside K8s
# https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer
# The LB details and status will be published in the service status.loadBalancer field
# Traffic from the external load balancer will be directed at the backend Pods
# The ElasticSearch cluster will be reachable via the LB IP at port 9200
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-loadbalancer
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-loadbalancer
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  type: LoadBalancer
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
  selector:
    k8s-app: elasticsearch-logging
